config/routes.rb
InitialRelease::Application.routes.draw do
  
  match '/login' => 'account#login', :as => 'login'
  match '/logout' => 'account#logout', :as => 'logout'
  match '/authenticate' => 'account#authenticate', :as => 'authenticate'
  resources :users do
    member do
      put 'enable'
    end
    resources :roles
  end

  match '/user/:username' => 'users#show_by_username', :as => 'show_user'
  match '/account/:id/:salt_key' => 'users#salt_account'
  
  root :to => "pages#show", :id => '1'#Page.all.first.id
  
  resources :pages
  
  match ':controller/:action/:id'

  

end

app/models/user.rb
require 'digest/sha2'
class User < ActiveRecord::Base
  has_and_belongs_to_many :roles
  
  attr_protected :hashed_password, :enabled
  attr_accessor :password
  validates_presence_of :username, :message => '^укажите свое имя'
  validates_presence_of :email, :message => '^укажите свой email'
  validates_presence_of :password, :if => :password_required?, :message => '^укажите пароль'
  validates_presence_of :password_confirmation, :if => :password_required?, :message => '^необходимо указать пароль повторно'
  
  validates_confirmation_of :password, :if => :password_required?, :message => '^пароль не совпадает с подтверждением'
  validates_uniqueness_of :username, :case_sensitive => false, :message => '^пользователь с таким именем уже зарегистрирован'
  validates_uniqueness_of :email, :case_sensitive => false, :message => '^email уже используется'
  validates_length_of :username, :within => 3..64, :message => '^имя должно содержать больше 3 символов'
  validates_length_of :email, :within => 5..128, :message => '^email должен содержать больше 3 символов'
  validates_length_of :password, :within => 4..20, :if => :password_required?, :message => '^пароль должен быть длинее 3 символов'
  validates_length_of :profile, :maximum => 1000, :message => '^слишком много информации'
  
  def before_save
    self.hashed_password = User.encrypt(password) if !self.password.blank?
  end
  
  def password_required?
    self.hashed_password.blank? || !self.password.blank?
  end
  
  def self.encrypt(string)
   return Digest::SHA256.hexdigest(string)
  end
  
  def self.authenticate(username, password)
    find_by_username_and_hashed_password_and_enabled_and_salted(username, User.encrypt(password), true, true)
  end

  def has_role?(rolename)
    self.roles.find_by_name(rolename) ? true : false
  end

  def check_role(role)
    unless is_logged_in? && @logged_in_user.has_role?(role)
      flash[:error] = "У недостаточно прав для данной операции"
      redirect_to :controller => 'account', :action => 'login'
    end
  end

  def check_administrator_role
    check_role('Administrator')
  end

  def self.random_string(len)
   #generate a random password consisting of strings and digits
   chars = ("a".."z").to_a + ("A".."Z").to_a + ("0".."9").to_a
   newpass = ""
   1.upto(len) { |i| newpass << chars[rand(chars.size-1)] }
   return newpass
 end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :check_administrator_role, :except => [:new, :create, :salt_account, :index, :show] #, :only => [:index, :destroy, :enable]

  def index
    @users = User.find(:all)
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def show_by_username
    @user = User.find_by_username(params[:username])
    render :action => 'show'
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    @user.salt_key = User.random_string(50)
    if @user.save
      Sender.salt_account(@user).deliver      
      flash[:notice] = "Аккаунт успешно создан, для активации пройдите, пожалуйста по ссылке, которая была отправлена вам на email"
      redirect_to :root
    else
      render :action => 'new'
    end
  end
  
  def edit
    @user = logged_in_user
  end
  
  def update
    @user = User.find(logged_in_user)
    if @user.update_attributes(params[:user])
      flash[:notice] = "User updated"
      redirect_to :action => 'show', :id => logged_in_user
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    if @user.update_attribute(:enabled, false)
      flash[:notice] = "Пользователь заблокирован"
    else
      flash[:error] = "There was a problem disabling this user."
    end
    redirect_to :action => 'index'
  end
  
  def enable
    @user = User.find(params[:id])
    if @user.update_attribute(:enabled, true)
      flash[:notice] = "Пользователь активен"
    else
      flash[:error] = "There was a problem enabling this user."
    end
    redirect_to :action => 'index'
  end
  
  def salt_account
    @user = User.find(params[:id])
    if params[:salt_key] && @user.salt_key == params[:salt_key]
      @user.salted = true
      @user.save
      self.logged_in_user = @user
      flash[:notice] = "Ваш аккаунт успешно активирован!"
    end    
    redirect_to :root
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.haml
%tr{:class=>"#{cycle('odd', 'even')}"}
	%td
		= link_to user.username, user_path(user)
	- if logged_in_user.has_role?('Administrator')
		%td
			= user.email
	%td
		= user.enabled ? 'да' : 'нет'
		- if logged_in_user.has_role?('Administrator')
			-  if user.enabled
				[
				= link_to('нет', user_url(user.id), :method => :delete)
				]
			- else
				[
				= link_to('да', enable_user_url(user.id), :method => :put)
				]
	%td
		= user.salted ? 'да' : 'нет'
	%td
		%ul{:style=>'padding:0;margin:0;list-style-type:none;'}
			- user.roles.each do |role|
				%li= role.alias
		- if logged_in_user.has_role?('Administrator')
			[
			= link_to 'изменить', user_roles_path(user)
			]

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#➥</h1>
<p>Find me in app/views/users/➥.html.erb</p>

app/views/users/edit.html.erb
<h2>Edit your account</h2>
<p><%= link_to 'Show my profile', user_path(@user) %></p>
<%= error_messages_for :user %>
<% form_for :user,
:url => user_url(@user),
:html => { :method => :put } do |f| -%>
<p>Email:<br /><%= f.text_field :email, :size => 60 %></p>
<p>Password:<br /><%= f.password_field :password, :size => 60 %></p>
<p>Password Confirmation:<br />
<%= f.password_field :password_confirmation, :size => 60 %></p>
<p>Profile:<br /><%= f.text_area :profile, :rows => 6, :cols => 60 %></p>
<%= submit_tag 'Save' %>
<% end -%>

app/views/users/index.html.haml
%table.main
	%tr
		%td
			%h2 Пользователи
	%tr
		%td
			.body
				%table{ :id=>'users', :width=>'100%'}
					%tr
						%th Имя пользователя
						- if logged_in_user.has_role?('Administrator')
							%th Email
						%th Разрешен
						%th Активирован
						%th Полномочия
					= render :partial => 'user', :collection => @users
	%tr
		%td
			.bottom &nbsp;

app/views/users/new.html.haml
%table.main
	%tr
		%td
			%h2 Регистрация
	%tr
		%td
			.body
				= error_messages_for :user
				- form_for :user, :url => users_path do |f|
					%p
						Имя пользователя:
						%br/
						= f.text_field :username, :size => 60, :class=>"text ui-widget-content ui-corner-all"
					%p
						Email:
						%br/
						= f.text_field :email, :size => 60, :class=>"text ui-widget-content ui-corner-all"
					%p
						Пол:
						%br/
						%span{:style=>"line-height:5px;"} женский
						= radio_button("user", "sex", "false")
						мужской
						= radio_button("user", "sex", "true")
					%p
						Телефон:
						%br/
						= f.text_field :phone, :size => 60, :class=>"text ui-widget-content ui-corner-all"
					%p
						Адрес:
						%br/
						= f.text_field :address, :size => 60, :class=>"text ui-widget-content ui-corner-all"
					%p
						Пароль:
						%br/
						= f.password_field :password, :size => 60, :class=>"text ui-widget-content ui-corner-all"
					%p
						Подтверждение пароля:
						%br/
						= f.password_field :password_confirmation, :size => 60, :class=>"text ui-widget-content ui-corner-all"
					%p
						Краткая информация о себе:
						%br/
						= f.text_area :profile, :rows => 6, :cols => 60, :class=>"text ui-widget-content ui-corner-all"
					= submit_tag 'регистрация', :class=>'but'
	%tr
		%td
			.bottom &nbsp;

app/views/users/show.html.haml
%table.main
	%tr
		%td
			%h2 Профиль пользователя
	%tr
		%td
			.body
				= link_to 'к списку пользователей', users_path
				%p
					Имя пользователя: 
					= @user.username
				- if logged_in_user.has_role?('Administrator')
					%p
						Email: 
						= @user.email
					%p
						Телефон: 
						= @user.phone
					%p
						Адрес: 
						= @user.address
				%p 
					Зарегистрирован:  
					= @user.created_at.strftime("%d.%m.%Yг.")
				%p
					Последний визит:  
					= @user.last_login_at.strftime("%d.%m.%Yг.") if @user.last_login_at
				%p
					Информация о пользователе:
				%p{:style=>'margin-left:30px;'}
					= @user.profile
	%tr
		%td
			.bottom &nbsp;

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>